IO04 2.2.1
HL7-cz/cz-core pull request #24
Opened 2024-12-23 09:26 UTC by pvrana

IO04 2.2.1 - Implementation of CSS stylesheet, english translation and adding HL7 EU base dependencies.

2024-12-23 12:30 UTC, kruzikh requested changes
Prosím o úpravu dle jednotlivých komentářů

2024-12-23 12:30 UTC, kruzikh commented on input/fsh/profiles/patient.fsh
I propose to create:
Base profile: CZ_Patient which will be based on PatientEu
and also a core profile CZ_PatientCore which will be baesd on PatientEuCore.

2024-12-23 12:30 UTC, kruzikh commented on input/fsh/profiles/practitioner.fsh
Here, we should follow EU base and core profile as well.

2024-12-23 12:30 UTC, kruzikh commented on input/fsh/profiles/practitionerRole.fsh
Here we should follow Eu base and core.

2025-01-09 19:32 UTC, pvrana commented on input/pagecontent/identifiers.md
Všechny poznámky jsem zapracovala do nové verze stránky.

2025-01-09 19:34 UTC, pvrana commented on input/fsh/profiles/practitionerRole.fsh
Two profiles are created.

2025-01-11 07:09 UTC, kruzikh approved these changes
Thank you for reflecting the comments. However, some details still would have to be re-discussed.

2025-01-11 07:10 UTC, merged